# config
server:
  servlet: #/api/v1
    context-path: ""
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: nguyenxuanmanh2992003@gmail.com
    password: txoklgxiwyeikode  # Xóa dấu cách
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  application:
    name: project-tn
  datasource:
    url: jdbc:mysql://localhost:3306/db_check_trung_tai_lieu
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  swagger-ui:
    path: /swagger-ui.html
jwt:
  expiryHour: 1
  expiryDay: 14
  secretKey: zzkpqZ1eUo/udLOYXr+/KVcKguT5f2eulxDE/dKjxOWWjsADWEyIBWyUP8EdFZUz
  refreshKey: nvev8yUsz4hl1wCuSCkvQO+T6NO+ecGjWSBJKRf7N0SuDArEeTPHPHBK1xPe0fAw
